const data = [
    { title: 'A', description: 'This is the description for A.' },
    { title: 'B', description: 'This is the description for B.' },
    { title: 'C', description: 'This is the description for C.' },
    { title: 'D', description: 'This is the description for D.' },
    { title: 'E', description: 'This is the description for E.' },
    { title: 'F', description: 'This is the description for F.' },
    { title: 'G', description: 'This is the description for G.' },
    { title: 'H', description: 'This is the description for H.' },
    { title: 'I', description: 'This is the description for I.' },
    { title: 'J', description: 'This is the description for J.' },
    { title: 'K', description: 'This is the description for K.' },
    { title: 'L', description: 'This is the description for L.' },
    { title: 'M', description: 'This is the description for M.' },
    { title: 'N', description: 'This is the description for N.' },
    { title: 'O', description: 'This is the description for O.' },
    { title: 'P', description: 'This is the description for P.' },
    { title: 'Q', description: 'This is the description for Q.' },
    { title: 'R', description: 'This is the description for R.' },
    { title: 'S', description: 'This is the description for S.' },
    { title: 'T', description: 'This is the description for T.' },
    { title: 'U', description: 'This is the description for U.' },
    { title: 'V', description: 'This is the description for V.' },
    { title: 'W', description: 'This is the description for W.' },
    { title: 'X', description: 'This is the description for X.' },
    { title: 'Y', description: 'This is the description for Y.' },
    { title: 'Z', description: 'This is the description for Z.' },
];

export default data